default: &default
  store_options:
    # Cap age of oldest cache entry to fulfill retention policies
    # max_age: <%= 60.days.to_i %>
    max_size: <%= 256.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
  database:
    adapter: postgresql
    encoding: unicode
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
    database: <%= ENV["RDS_DB_NAME"] %>
    username: <%= ENV["RDS_USERNAME"] %>
    password: <%= ENV["RDS_PASSWORD"] %>
    host: <%= ENV["RDS_HOSTNAME"] %>
    port: <%= ENV["RDS_PORT"] || 5432 %>
